##-------------------------------
# General Site Settings
title: Georgeomics
logo: # You can add own logo. For example '/images/logo.png'.
description: "A Site by George Zaragoza"
hero-image: '/images/205.jpg'
baseurl: '' # The subpath of your site, e.g. /blog
url: "https://georgeomics.github.io/personalsite" # The base hostname & protocol for your site, e.g. http://example.com

blog-theme: dark # You can use a `dark` or `light` theme.

github_username:  georgeomics

#-------------------------------
# Authors Settings
author:
  name:     George Zaragoza
  bio:      George Zaragoza is currently a PhD student in Integrative and Conservation  Biology at the University of Central Florida. 
  
  location: Orlando, FL
  avatar:   /images/headshot_1.jpg
  twitter:  https://twitter.com/georgeomics
  google:  https://scholar.google.com/citations?user=ADaaSzkAAAAJ
  linkedin:  https://www.linkedin.com/in/georgezaragoza/
  cover:    /images/214.jpg
  cv: https://drive.google.com/uc?export=download&id=1uECrnd-qRaDyqtxjRZuS9DUQeXngH1vY


#-------------------------------
# Featured Slider
#slider: true # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.


#-------------------------------
# Contact Settings
contact:
  email: george.zaragoza@gmail.com # Add your email for contant form
  description: "Feel free to send me a message if you want to get in touch." # Add a description of your form

# NOTE
# Clifford theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other possible icons can be found at https://ionicons.com
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/georgeomics"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
#- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {icon: "ion-logo-google", link: "https://scholar.google.com/citations?user=ADaaSzkAAAAJ"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/georgezaragoza/"}
#- {icon: "ion-logo-github", link: "https://github.com/georgeomics"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
#mailchimp-text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
#mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed


###########################################


#Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
